//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSI_test.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportLog
    {
        public int ExportId { get; set; }
        public string ExportName { get; set; }
        public System.DateTime ExportDateTime { get; set; }
        public string ExportUserName { get; set; }
        public string ExportLocalName { get; set; }
    }
}
